run_test_task:
  name: Run test
  alias: run_test
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  #env:
    #PATH: ${PATH}:/Users/admin/fsl/bin
  clone_script:
    - echo SKIP CLONE
  download_fsl_script:
    - curl "https://git.fmrib.ox.ac.uk/fsl/conda/installer/-/raw/main/fsl/installer/fslinstaller.py?ref_type=heads&inline=false" --output fslinstaller.py
  install_fsl_script:
    - python3.11 fslinstaller.py -d /Users/admin/fsl
  reload_script:
    - echo $PATH
    - source /Users/admin/.zprofile
    - echo $PATH
  check_script:
    - clang++ -v
    - ls -la /Users/admin/fsl
  install_amico_script:
    - python3.11 -m pip install dmri-amico --no-cache-dir --force-reinstall --verbose
