run_test_task:
  name: Run test
  alias: run_test
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  clone_script:
    - echo SKIP CLONE
  env:
    PATH: ${PATH}:/opt/homebrew/opt/python@3.11/bin
  install_requirements_script:
    - brew install python@3.11
  install_amico_script:
    - pip install dmri-amico --no-cache-dir --force-reinstall
