run_test_task:
  name: Run test
  alias: run_test
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  env:
    CC: /Users/admin/fsl/clang
    CXX: /Users/admin/fsl/clang++
  clone_script:
    - echo SKIP CLONE
  download_fsl_script:
    - curl "https://git.fmrib.ox.ac.uk/fsl/conda/installer/-/raw/main/fsl/installer/fslinstaller.py?ref_type=heads&inline=false" --output fslinstaller.py
  install_fsl_script:
    - python3.11 fslinstaller.py -d /Users/admin/fsl
  check_script:
    - echo "$CC"
    - echo "$CXX"
    - clang++ -v
    - $CC -v
    - $CXX -v
  install_amico_script:
    - python3.11 -m pip install dmri-amico --no-cache-dir --force-reinstall
