run_test_task:
  name: Run test
  alias: run_test
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  env:
    PATH: ${PATH}:/opt/homebrew/opt/python@3.11/bin
  clone_script:
    - echo SKIP CLONE
  install_amico_script:
    - python3.11 -m pip install dmri-amico --no-cache-dir --force-reinstall
